### PR TITLE
Wc ecoli hwrn

### PR DESCRIPTION
**Pull request by Hocnonsense**

### CODE REVIEW

**Comment by 1fish2** [comment]
Thank you for your interest, @Hocnonsense!

As the README says, we're not taking Pull Requests for this publication snapshot. The only changes will be to maintain repeatability.

**Comment by Hocnonsense** [comment]
OK. But I think I’ve found some bugs.

1. In `wholecell.fireworks.firetasks.FitSimDataTask`, line 14:
The `FireTaskBase` class will check params in `__init__`. I found `[ "cpus", debug", "cached", “cached_data"]` should be appended to `optional_params`.
2. 

发送自 Windows 10 版邮件应用

发件人: Jerry Morrison
发送时间: 2020年8月10日 04:18
收件人: CovertLab/WholeCellEcoliRelease
抄送: Hocnonsense; Mention
主题: Re: [CovertLab/WholeCellEcoliRelease] Wc ecoli hwrn (#4)

Thank you for your interest, @Hocnonsense!
As the README says, we're not taking Pull Requests for this publication snapshot. The only changes will be to maintain repeatability.

**Comment by Hocnonsense** [comment]
OK. But I think I’ve found some bugs.

 

1.   In `wholecell.fireworks.firetasks.FitSimDataTask`, line 14:
The `FireTaskBase` class will check params in `__init__`. I found `[ "cpus", debug", "cached", “cached_data"]` should be appended to `optional_params`.

2.    In `from reconstruction.ecoli.knowledge_base_raw import KnowledgeBaseEcoli`, line 185:
The `json.loads(row['value'])` is a list for “KcatEndoRNasesFullRNA” in file ‘WholeCellEcoliRelease\\reconstruction\\ecoli\\flat\\parameters.tsv’, as the ‘value’ is ‘[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]'

3.   In `raw_data.condition.nutrient`, 
the name is not ‘lower bound’ but ‘lower bound (units.mmol / units.g / units.h)'


Is these mentioned below bug in py27? I found these bugs in py37. But I have no idea about problem.3 now.


Thanks!

PS: I’m sorry because I clicked `ctrl` + `Enter` in a reflect action, which send the e-mail instead of enter a new line…

发送自 Windows 10 版邮件应用

发件人: Jerry Morrison
发送时间: 2020年8月10日 04:18
收件人: CovertLab/WholeCellEcoliRelease
抄送: Hocnonsense; Mention
主题: Re: [CovertLab/WholeCellEcoliRelease] Wc ecoli hwrn (#4)

Thank you for your interest, @Hocnonsense!
As the README says, we're not taking Pull Requests for this publication snapshot. The only changes will be to maintain repeatability.

**Comment by 1fish2** [comment]
Do let us know what your goal is, then we can discuss approaches in a team meeting.

This code snapshot forked from our working repository a couple years ago, so improving it would probably not be productive. The working repository had a lot of changes to run in Python 3.8, plus all the modeling additions and other improvements over those years, but it's very much a work in progress. This release snapshot only runs with Python 2.7 and with the specific frozen versions of pip packages as listed in `requirements.txt`.

You are correct that the FireTaskBase params are wrong in FitSimDataTask. They're wrong in some other tasks as well. That's been fixed in the working repo while in this snapshot the bug has no impact because that release of FireWorks didn't check params declarations.

I'm not sure what went wrong in items (2) and (3) in your tests, but Python 3 has different rules for JSON decoding and text decoding. Some of the .tsv files contain column names with units in parentheses. The `JsonReader` code and other I/O code applies the units to the values.

**Comment by Hocnonsense** [comment]
Ohhhh... It seems to be a mistake to merge this 2 commits. I'm sorry to found this request so lately.

My goal is to repeat this work on my computer, and understand how it works. Maybe I can simulate the growth of LUCA? 

Now I can run `runFitter.py` in my new py3.7 environment successfully. 
However, when runing the `runSim.py`, I'm troubled by `sim.loggers["Shell"]`.
In detail, when initialising `EcoliSimulation(**options)`
https://github.com/CovertLab/WholeCellEcoliRelease/blob/627a5c52083fe0812165c9511b159e7e09f05fcf/wholecell/fireworks/firetasks/simulation.py#L53, 
1.  the param `_shellColumnHeaders` is set in `EcoliSimulation`
https://github.com/CovertLab/WholeCellEcoliRelease/blob/627a5c52083fe0812165c9511b159e7e09f05fcf/models/ecoli/sim/simulation.py#L96-L104 
and override the `Simulation._shellColumnHeaders` and something like "Dry mass (fg)" are added. However, when initialising `self.loggers["Shell"]`
https://github.com/CovertLab/WholeCellEcoliRelease/blob/627a5c52083fe0812165c9511b159e7e09f05fcf/wholecell/sim/simulation.py#L181, 
2. the param `columnSpecs`
https://github.com/CovertLab/WholeCellEcoliRelease/blob/627a5c52083fe0812165c9511b159e7e09f05fcf/wholecell/loggers/shell.py#L31-L33
don't has the key "Dry mass (fg)". So, `self.loggers["Shell"].initialize(self)` cannot find the `spec for `header` "Dry mass (fg)".
https://github.com/CovertLab/WholeCellEcoliRelease/blob/627a5c52083fe0812165c9511b159e7e09f05fcf/wholecell/loggers/shell.py#L43-L52
thus it raise the Exception.

Would you mind tell me how to solve it?
Thanks!

**Comment by 1fish2** [comment]
> My goal is to repeat this work on my computer, and understand how it works. Maybe I can simulate the growth of LUCA?

Ah! Nice.

Please see these instructions for setting up a Python virtual environment:

* https://github.com/CovertLab/WholeCellEcoliRelease/blob/master/docs/dev-tools.md
* https://github.com/CovertLab/WholeCellEcoliRelease/blob/master/docs/create-pyenv.md

This explains how to set up a virtual environment containing Python 2.7 and the right versions of the pip libraries without disturbing your Python 3.7 environment. `pyenv virtualenv` is very handy. You can switch between different versions combinations of Python and pip versions.

The problems you're encountering with the input data might be because I/O, text strings, and the json library work differently in Python 3. E.g. Python 2 mixes up `str` with `bytes`, and file objects and csv handle text decoding quite differently. Or the problems might be due to other Python 2/3 differences like `dict` access iterators, `zip`/`range`/`next` iterators, metaclasses, etc. (Separately, string hash in Python 3 adds extra "salt" bits that vary from run to run, so `hash` becomes inappropriate for pseudo-random seeds. The working code base switched to a CRC.) But I have not seen those symptoms before.

Using Python 2, you can avoid debugging one problem after another that were caused by Python 2/3 compatibility.

**Comment by Hocnonsense** [comment]
Thanks!

I've successfully solved these compatibility probelms, and run `runFitter.py` and `runSim.py` on a python3.7 environment created by conda!

**Comment by Hocnonsense** [comment]
Thanks for your advice and notices!

But I've already remove those problems, and able to run `runFitter.py` and `runSim.py` successfully :)

**Comment by Hocnonsense** [comment]
Hi~ I'm trapped into another trouble, would you mind help me?

I'm attempting to use the Fireworks, and I've create an account of mongodb. However, when "Make the Configuration files for FireWorks", I cannot run `lpad -l my_launchpad.yaml reset`. My `my_launchpad.yaml` file is like this:
```yaml
logdir: ...\fw\logs\launchpad
host: mongodb+srv://wcecoli.mpwh6.azure.mongodb.net
uri_mode: true
name: wcecoli
username: hwrn
password: <password>
port:
strm_lvl: INFO
user_indices: []
wf_user_indices: []
```
My mongodb cluster is `wcecoli`, so what would the file be like? 

Thanks!

**Comment by 1fish2** [comment]
Ah, yes. I just recently learned that [mlab.com](https://mlab.com) won't create new accounts. It points to [MongoDB Atlas](https://cloud.mongodb.com/) instead, which works differently.

The key difference is that it creates a cluster of 3 servers instead of a single server. Connecting to a cluster is different.

Please try this.

**On the Atlas website cloud.mongodb.com**
* If needed, set "Network Access" to Allow Access from the relevant IP address range.
* If needed, edit the user to add "Atlas Admin" user privileges. I think this is needed to be able to create a DB in the server.
* Under "Clusters" click CONNECT, and choose the connection method `Connect your application`.
  * Pick the "driver" "Python 3.6 or later" or "Python 3.11.0 or later" depending on your pymongo version.
  * Copy the connection string, e.g. (assuming the DB user is `wc_ecoli` and the cluster is `wcecoli`)
     `mongodb+srv://wc_ecoli:<password>@wcecoli.mpwh6.azure.mongodb.net/<dbname>?retryWrites=true&w=majority`

**On your computer**
* Install dnspython to be able to access mongo clusters:
  `pip install dnspython`
* Compute the URL-quoted password for the DB user:
  `python -c "import urllib.parse; print(urllib.parse.quote('WCECOLI USER PASSWORD'))"`
* Run FireWorks' `lpad init -u` command to create the `my_launchpad.yaml` file in "Connect via a URI" mode, pasting in the connection string from Atlas, with substitutions for the quoted password and a chosen DB name, say `ecoli1`:
    ```
    lpad init -u
    Enter host parameter: mongodb+srv://wc_ecoli:URL_QUOTED_WCECOLI_USER_PASSWORD@clusterf.9zutr.mongodb.net/ecoli1
    Enter ssl_ca_file parameter:
    Enter authsource parameter: admin
    ```
* `lpad reset`

I expect the `my_launchpad.yaml` file will come out like this:

```yaml
authsource: admin
host: mongodb+srv://wc_ecoli:URL_QUOTED_WCECOLI_USER_PASSWORD@wcecoli.mpwh6.azure.mongodb.net/ecoli1
logdir: null
mongoclient_kwargs: {}
name: null
password: null
port: null
ssl: false
ssl_ca_certs: null
ssl_certfile: null
ssl_keyfile: null
ssl_pem_passphrase: null
strm_lvl: INFO
uri_mode: true
user_indices: []
username: null
wf_user_indices: []
```

You can change the `logdir` and other settings.

**Pull request closed without merging**
